#!/bin/bash

if [ "$SLIMERJSLAUNCHER" == "" ]
then
    SLIMERJSLAUNCHER=`command -v firefox`
    if [ "$SLIMERJSLAUNCHER" == "" ]
    then
        SLIMERJSLAUNCHER=`command -v xulrunner`
        if [ "$SLIMERJSLAUNCHER" == "" ]
        then
            echo "SLIMERJSLAUNCHER environment variable is missing. Set it with the path to Firefox or XulRunner"
            exit 1
        fi
    fi
fi

if [ ! -x "$SLIMERJSLAUNCHER" ]
then
    echo "SLIMERJSLAUNCHER environment variable does not contain an executable path. Set it with the path to Firefox"
    exit 1
fi

if [ "$1" == "--help" -o "$1" == "-h" ]
then
    #echo "  --cookies-file=<file>              Sets the file name to store the persistent"
    #echo "                                     cookies."
    #echo "  --config=<file>                    Load the given configuration file"
    #echo "                                     (JSON formated)"
    #echo "  --debug=[yes|no]                   Prints additional warning and debug message"
    #echo "                                     (default is no)"
    #echo "  --disk-cache=[yes|no]              Enables disk cache (default is no)."
    echo "  --help or -h                       Show this help"
    #echo "  --ignore-ssl-errors=[yes|no]       Ignores SSL errors (default is no)."
    #echo "  --load-images=[yes|no]             Loads all inlined images (default is yes)"
    #echo "  --local-storage-path=<path>        Specifies the location for offline local"
    #echo "                                     storage"
    #echo "  --local-storage-quota=<number>     Sets the maximum size of the offline"
    #echo "                                     local storage (in KB)"
    #echo "  --local-to-remote-url-access=[yes|no] Allows local content to access remote"
    #echo "                                        URL (default is no)"
    #echo "  --max-disk-cache-size=<number>     Limits the size of the disk cache (in KB)"
    #echo "  --output-encoding=<enc>            Sets the encoding for the terminal output"
    #echo "                                     (default is 'utf8')"
    #echo "  --remote-debugger-port=<number>    Starts the script in a debug harness and"
    #echo "                                     listens on the specified port"
    #echo "  --remote-debugger-autorun=[yes|no] Runs the script in the debugger immediately"
    #echo "                                     (default is no)"
    #echo "  --proxy=<proxy url>                Sets the proxy server"
    #echo "  --proxy-auth=<username:password>   Provides authentication information for the"
    #echo "                                     proxy"
    #echo "  --proxy-type=[http|socks5|none]    Specifies the proxy type (default is http)"
    #echo "  --script-encoding=<enc>            Sets the encoding used for the starting"
    #echo "                                     script (default is utf8)"
    #echo "  --web-security=[yes|no]            Enables web security (default is yes)"
    #echo "  --ssl-protocol=[SSLv3|SSLv2|TLSv1|any]  Sets the SSL protocol"
    #echo "  --ssl-certificates-path=<path>     Sets the location for custom CA certificates"
    echo "  --version or v                     Prints out SlimerJS version"
    #echo "  --webdriver or --wd or -w          Starts in 'Remote WebDriver mode' (embedded"
    #echo "                                     GhostDriver) '127.0.0.1:8910'"
    #echo "  --webdriver=[<IP>:]<PORT>          Starts in 'Remote WebDriver mode' in the"
    #echo "                                     specified network interface"
    #echo "  --webdriver-logfile=<file>         File where to write the WebDriver's Log "
    #echo "                                     (default 'none') (NOTE: needs '--webdriver')"
    #echo "  --webdriver-loglevel=[ERROR|WARN|INFO|DEBUG] WebDriver Logging Level "
    #echo "                                 (default is 'INFO') (NOTE: needs '--webdriver')"
    #echo "  --webdriver-selenium-grid-hub=<url> URL to the Selenium Grid HUB (default is"
    #echo "                                      'none') (NOTE: needs '--webdriver') "
    exit 0
fi

#retrieve full path (firefox on macos needs it)
pushd `dirname $0` > /dev/null
SCRIPTDIR=`pwd`
popd > /dev/null

# retrieve list of existing environment variable, because Mozilla doesn't provide an API to get this
# list
LISTVAR=""
ENVVAR=`env`;
for v in $ENVVAR; do
    IFS='=' read -a var <<< "$v"
    LISTVAR="$LISTVAR,${var[0]}"
done

"$SLIMERJSLAUNCHER" -app $SCRIPTDIR/application.ini -purgecaches --envs "$LISTVAR" "$@"

